backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img
locale: 'it'

i18n:
  structure: single_file
  locales: [ 'en', 'it' ]
  default_locale: 'en'

collections:
  - name: 'blog'
    i18n: true
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'blog-post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Featured Post', name: 'featuredpost', widget: 'boolean' }
      - { label: 'Featured Image', name: 'featuredimage', widget: image }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'index-page' }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - {
            label: Mainpitch,
            name: mainpitch,
            widget: object,
            fields:
              [
                { label: Title, name: title, widget: string },
                { label: Description, name: description, widget: text },
              ],
          }
          - { label: Description, name: description, widget: string }
          - {
            label: Intro,
            name: intro,
            widget: object,
            fields:
              [
                { label: Heading, name: heading, widget: string },
                { label: Description, name: description, widget: text },
                {
                  label: Blurbs,
                  name: blurbs,
                  widget: list,
                  fields:
                    [
                      { label: Image, name: image, widget: image },
                      { label: Text, name: text, widget: text },
                    ],
                },
              ],
          }
          - {
            label: Main,
            name: main,
            widget: object,
            fields:
              [
                { label: Heading, name: heading, widget: string },
                { label: Description, name: description, widget: text },
                {
                  label: Image1,
                  name: image1,
                  widget: object,
                  fields:
                    [
                      { label: Image, name: image, widget: image },
                      { label: Alt, name: alt, widget: string },
                    ],
                },
                {
                  label: Image2,
                  name: image2,
                  widget: object,
                  fields:
                    [
                      { label: Image, name: image, widget: image },
                      { label: Alt, name: alt, widget: string },
                    ],
                },
                {
                  label: Image3,
                  name: image3,
                  widget: object,
                  fields:
                    [
                      { label: Image, name: image, widget: image },
                      { label: Alt, name: alt, widget: string },
                    ],
                },
              ],
          }
      - file: 'src/pages/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'about-page' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: 'src/pages/products/index.md'
        label: 'Products Page'
        name: 'products'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'product-page' }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
          - {
            label: Intro,
            name: intro,
            widget: object,
            fields:
              [
                { label: Heading, name: heading, widget: string },
                { label: Description, name: description, widget: text },
                {
                  label: Blurbs,
                  name: blurbs,
                  widget: list,
                  fields:
                    [
                      { label: Image, name: image, widget: image },
                      { label: Text, name: text, widget: text },
                    ],
                },
              ],
          }
          - {
            label: Main,
            name: main,
            widget: object,
            fields:
              [
                { label: Heading, name: heading, widget: string },
                { label: Description, name: description, widget: text },
                {
                  label: Image1,
                  name: image1,
                  widget: object,
                  fields:
                    [
                      { label: Image, name: image, widget: image },
                      { label: Alt, name: alt, widget: string },
                    ],
                },
                {
                  label: Image2,
                  name: image2,
                  widget: object,
                  fields:
                    [
                      { label: Image, name: image, widget: image },
                      { label: Alt, name: alt, widget: string },
                    ],
                },
                {
                  label: Image3,
                  name: image3,
                  widget: object,
                  fields:
                    [
                      { label: Image, name: image, widget: image },
                      { label: Alt, name: alt, widget: string },
                    ],
                },
              ],
          }
          - {
            label: Testimonials,
            name: testimonials,
            widget: list,
            fields:
              [
                { label: Quote, name: quote, widget: string },
                { label: Author, name: author, widget: string },
              ],
          }
          - { label: Full_image, name: full_image, widget: image }
          - {
            label: Pricing,
            name: pricing,
            widget: object,
            fields:
              [
                { label: Heading, name: heading, widget: string },
                { label: Description, name: description, widget: string },
                {
                  label: Plans,
                  name: plans,
                  widget: list,
                  fields:
                    [
                      { label: Plan, name: plan, widget: string },
                      { label: Price, name: price, widget: string },
                      { label: Description, name: description, widget: string },
                      { label: Items, name: items, widget: list },
                    ],
                },
              ],
          }

  - name: 'instructors'
    label: 'Istruttori'
    label_singular: 'Istruttore'
    i18n: true
    description: 'Istruttori dei corsi'
    folder: 'src/content/instructors'
    create: true
    slug: '{{firstName}}-{{lastName}}'
    extension: json
    format: json
    fields:
      - { label: 'Nome', name: 'firstName', widget: 'string', i18n: duplicate, required: true }
      - { label: 'Cognome', name: 'lastName', widget: 'string', i18n: duplicate, required: true }

  - name: 'courses'
    label: 'Corsi'
    label_singular: 'Corso'
    i18n: true
    description: 'Corso curriculare'
    folder: 'src/content/courses'
    create: true
    slug: '{{venue}}-{{discipline}}'
    extension: json
    format: json
    fields:
      - { label: 'Sala', name: 'venue', widget: 'string', i18n: duplicate, required: true }
      - { label: 'Disciplina', name: 'discipline', widget: 'string', i18n: duplicate, required: true }
      - { label: 'Istruttore', name: 'instructor', widget: 'relation', collection: 'instructors', value_field: '{{firstName}} {{lastName}}', search_fields: ['firstName', 'lastName'] }
      - label: 'Orari'
        name: 'hours'
        i18n: true
        widget: 'list'
        fields:
          - label: 'Lun'
            name: 'mon'
            widget: 'object'
            i18n: true
            fields:
              - { label: 'Attivo', name: 'active', widget: 'boolean', i18n: duplicate }
              - { label: 'Inizio', name: 'startTime', widget: 'datetime', i18n: duplicate, date_format: false, time_format: "hh:mm", format: "hh:mm" }
              - { label: 'Fine', name: 'endTime', widget: 'datetime', i18n: duplicate, date_format: false, time_format: "HH:mm", format: "hh:mm" }

  - name: 'config'
    label: 'Config'
    i18n:
      structure: single_file
    files:
      - name: 'menu'
        label: 'Menu'
        file: 'src/config/menu.yaml'
        i18n: true
        fields:
          - label: 'Voices'
            name: 'voices'
            widget: 'list'
            fields:
              - { label: 'label', name: 'Label', widget: 'string', i18n: true }
              - { label: 'route', name: 'Route', widget: 'string', i18n: true }

